apiVersion: v1
kind: Service   
metadata:
  name: eks-app-service
spec:
  selector:
    app.kubernetes.io/name: eks-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
    spec:
      containers:
      - name: eks-app-container
        image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:${{ github.sha }}
        ports:
          - protocol: TCP
            containerPort: 8080
